### PR TITLE
Fixed issue with Swift 4 syntax

### PR DESCRIPTION
**Pull request by AdamBCo**

### CODE REVIEW

**Comment by evermeer** [comment]
This is probably to fix this? https://github.com/melvitax/DateHelper/issues/72

but .rangeAt(1) is Swift 3 syntax you need to do .range(at:

see https://developer.apple.com/documentation/foundation/nstextcheckingresult/1416732-range
and https://github.com/search?l=Swift&q=org%3Aapple+foundation+swift+range%28at&type=Code&utf8=✓

**Comment by evermeer** [comment]
Why did you merge?
It should not be .rangeAt()
The Swift 4 syntax is .range(at:)
It's a weird swift bug that it tells you to use .rangeAt
You could work around it. See my last comment as #72

**Comment by melvitax** [comment]
Merged it by mistake but I have a fix that should fix this with a proper of statement

**Comment by evermeer** [comment]
That conditional compilation will probably not fix the issue. But I think the situation is rare so you might wait until it happens again.

I tried this syntax to in my EVReflection library but it still gave me problems. Not in the library itself, but in the library EVCloudKitDao which has EVReflection as a dependency. I could not publish it to cocoapods. Not even when I set every podspec to swift 4. I ended up removing the range(at: function completely.

**Pull request merged**
